apiVersion: v1
kind: Service
metadata:
  labels:
    app: wil42
  name: wil42
  namespace: dev
spec:
  type: NodePort
  selector:
    app: wil42
  ports:
    - name: wil42
      protocol : TCP
      port: 8888
      targetPort: 8888
      nodePort: 30080
